version: "2"
checks:
  identical-code:
    enabled: false
  config:
    threshold: 4
  similar-code:
    enabled: false
  config:
    threshold: 4
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
plugins:
  eslint:
    enabled: true
exclude_patterns:
  - "node_modules/"
  - "dist/"
  - "webpck.config.js"
  - "config/"
  - "coverage/"
  - "hooks/"
  - "__tests__/" #Confirm if this is appropraite
  - "__mocks__/"
  - "src/utils/nonPersistentData.js"
  