version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/mrm_front
      - /mrm_front/node_modules
  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
